### ISSUE TITLE
Raise the cost when not stock

### ISSUE THREAD

**Issue by Morphyum** [Morphyum/BrokenSalvagedMechs#1]
In the same spirit, would it be possible to increase the maintenance cost for modified chassis? I have observed in the mech bay that there is a "modified" tag which appears once the design is customised (=different vs stock), so it seems the game engine can recognize this. Maybe it would be possible to use this tag to increase maintenance cost for modified mech?

The idea behind this is to represent the daily tweaks and tuning effort needed to maintain functional a customised mech. As in the lore : modified designs are rares and expensives, so it would make sense to have increased maintenance cost to simulate that. Also it would encourage to keep stock design.

**Comment by umbravi** [comment]
That depends on what "Modified" means. Does modified point to a customized loadout, or custom hardpoint settings? If hardpoint settings, then I think your thoughts are on the right track.

**Comment by Morphyum** [comment]
Oh this was jsut a piece of text i copied to remind myself of the issue, not my own words :)

**Comment by Morphyum** [comment]
Out of scope
