### ISSUE TITLE
Salvaging whole mech with damage, not in parts.

### ISSUE THREAD

**Issue by umbravi** [Morphyum/BrokenSalvagedMechs#3]
I think this is out of the scope of this mod, but the above is what I'd like to implement. I'm thinking about forking, but I'd like to get a KT from you about the salvaging system: where should I look for the hooks? Also, I've not used Harmony before, so I'll need to come up to speed there as well.

**Comment by Morphyum** [comment]
Yea this is out of scope, You probably want to look at GenerateSalvage in the contract class and maybe AddMechPart in SimGameState to get an idea whats going on, but your ide sounds like you need to touch a lot of places.

**Comment by umbravi** [comment]
Thanks for the pointers!

**Comment by umbravi** [comment]
For reference: It appears that salvaging whole chassis is already in the code in GenerateSalvage() beginning line 2132: if (flag3).

There is nothing that sets flag3 to true, so it's just always false.
