### ISSUE TITLE
Salvaging mechs gives nothing

### ISSUE THREAD

**Issue by Tyler799** [Morphyum/BrokenSalvagedMechs#5]
Just tried with a couple missions, version 1.01 of this mod.

Before updating,  it worked fine. However, now it fails to give me anything when salvaging a mech. They don't go into inventory, they don't complete mechs or do anything. Mech salvage just disappears. 

Someone else reported the same issue with 1.0 and 1.01: https://www.reddit.com/r/BattleTechMods/comments/8lhtm7/mod_modtek_brokensalvagedmechs_v10_new_options/dzgt2zs/

**Comment by Morphyum** [comment]
on it right now

**Comment by Morphyum** [comment]
fixed in 1.0.2 the settings json was fucked up
